#include <tk/tkernel.h>
#include <tm/tmonitor.h>
#include <string.h>

#include "hal_data.h"
#include "usb_loader.h"
#include "video_source.h"
#include "fps_control.h"


#define USB_LOADER_TASK_PRIORITY      (11)
#define USB_LOADER_TASK_STACK_SIZE    (4096)
#define USB_LOADER_PARTITION_NUMBER   (0U)

#define USB_LOADER_SELECT_PATH        "/SELECT.TXT"

#define USB_LOADER_MAX_VIDEO_INDEX    (999U)
#define USB_LOADER_MAX_TARGET_FPS     (120U)

/* Let the lower-priority NPU (12) and IPC (20) tasks run during replay.
 * The bare-metal USB/FAT driver polls hardware; it does not sleep in the RTOS.
 */
#define USB_LOADER_FRAME_YIELD_MS     (1)

/* The throughput benchmark is diagnostic, not a prerequisite for playback. */
#ifndef USB_LOADER_ENABLE_RAW_BENCHMARK
#define USB_LOADER_ENABLE_RAW_BENCHMARK (0U)
#endif

volatile usb_loader_diagnostics_t g_usb_loader_diagnostics =
{
    .stream_frame_index = UINT32_MAX,
};

/* Keep downstream frame IDs increasing across USB replays. File offsets and
 * read profiling still use the zero-based frame_index local to each file.
 */
static uint32_t s_next_stream_frame_index;

/*
 * Raw USB benchmark uses the actual number of bytes
 * stored for one tightly-packed .Y56 frame.
 *
 * 224 x 168 x 2 = 75264 bytes
 * 75264 / 512 = 147 sectors
 */
#define USB_BENCHMARK_BLOCK_SIZE_BYTES    (512U)

#define USB_BENCHMARK_BLOCKS_PER_FRAME \
    (VIDEO_SOURCE_FILE_FRAME_BYTES / \
     USB_BENCHMARK_BLOCK_SIZE_BYTES)

#define USB_BENCHMARK_FRAME_COUNT         (300U)

/*
 * Read-only test area.
 * No data is written to the USB device.
 */
#define USB_BENCHMARK_START_BLOCK         (2048U)


LOCAL ID s_usb_loader_task_id = 0;

LOCAL FF_Disk_t s_usb_disk;

LOCAL rm_freertos_plus_fat_device_t s_usb_device =
{
    .sector_count      = 0U,
    .sector_size_bytes = 0U,
};

LOCAL uint8_t s_usb_mounted = 0U;

LOCAL void usb_loader_task_entry(INT stacd, void *exinf);

LOCAL fsp_err_t usb_loader_mount(
    usb_event_info_t * event_info);

LOCAL void usb_loader_unmount(void);

LOCAL T_CTSK s_usb_loader_task_ctsk =
{
    .tskatr  = TA_HLNG | TA_RNG3,
    .task    = usb_loader_task_entry,
    .itskpri = USB_LOADER_TASK_PRIORITY,
    .stksz   = USB_LOADER_TASK_STACK_SIZE,
};

LOCAL uint8_t usb_loader_read_config(
    uint32_t * selected_index,
    uint32_t * target_fps
);

LOCAL void usb_loader_make_video_path(
    uint32_t index,
    char path[12]
);

LOCAL size_t usb_loader_read_exact(
    FF_FILE * file,
    uint8_t * destination,
    size_t bytes_to_read
);

#if USB_LOADER_ENABLE_RAW_BENCHMARK
LOCAL void usb_loader_run_raw_benchmark(void);
#endif

LOCAL void usb_loader_stream_selected_video(void);


ER usb_loader_create(void)
{
    ID task_id;

    task_id = tk_cre_tsk(&s_usb_loader_task_ctsk);

    if (task_id < E_OK)
    {
        return (ER) task_id;
    }

    s_usb_loader_task_id = task_id;

    return E_OK;
}


ER usb_loader_start(void)
{
    if (s_usb_loader_task_id <= 0)
    {
        return E_ID;
    }

    return tk_sta_tsk(s_usb_loader_task_id, 0);
}


LOCAL fsp_err_t usb_loader_mount(
    usb_event_info_t * event_info)
{
    fsp_err_t err;
    FF_Error_t ff_err;

    if ((NULL == event_info) ||
        (NULL == event_info->p_context))
    {
        tm_putstring(
            (UB *)"[USB] mount failed: invalid context.\n"
        );

        return FSP_ERR_INVALID_POINTER;
    }

    /*
     * The HMSC callback context is the block-media USB
     * control structure generated by FSP.
     */
    rm_block_media_usb_instance_ctrl_t * block_media_ctrl =
        (rm_block_media_usb_instance_ctrl_t *)
        event_info->p_context;

    block_media_ctrl->device_address =
        event_info->device_address;

    tm_putstring(
        (UB *)"[USB] MediaInit...\n"
    );

    g_usb_loader_diagnostics.stage = USB_LOADER_MEDIA_INIT;
    err = RM_FREERTOS_PLUS_FAT_MediaInit(
        &g_rm_freertos_plus_fat0_ctrl,
        &s_usb_device
    );

    if (FSP_SUCCESS != err)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fsp_error = (int32_t) err;
        tm_printf(
            (UB *)"[USB] MediaInit failed: %d\n",
            err
        );

        return err;
    }

    tm_printf(
        (UB *)"[USB] media: sectors=%u sector_size=%u\n",
        s_usb_device.sector_count,
        s_usb_device.sector_size_bytes
    );


#if USB_LOADER_ENABLE_RAW_BENCHMARK
    /*
    * Measure raw USB/HMSC -> SDRAM throughput
    * before FreeRTOS+FAT filesystem processing.
    */
    tm_putstring(
        (UB *)"[USB-Bench] raw block-media test start.\n"
    );

    g_usb_loader_diagnostics.stage = USB_LOADER_RAW_BENCHMARK;
    usb_loader_run_raw_benchmark();

    tm_putstring(
        (UB *)"[USB-Bench] raw block-media test end.\n"
    );
#endif


    /*
    * The USB device capacity is determined at runtime.
    */
    g_rm_freertos_plus_fat0_disk_cfg.device.sector_count =
        s_usb_device.sector_count;

    g_rm_freertos_plus_fat0_disk_cfg.device.sector_size_bytes =
        s_usb_device.sector_size_bytes;

    tm_printf(
        (UB *)"[USB] disk cfg: sectors=%u sector_size=%u cache=%u\n",
        g_rm_freertos_plus_fat0_disk_cfg.device.sector_count,
        g_rm_freertos_plus_fat0_disk_cfg.device.sector_size_bytes,
        g_rm_freertos_plus_fat0_disk_cfg.cache_size_bytes
    );

    tm_putstring(
        (UB *)"[USB] DiskInit...\n"
    );

    g_usb_loader_diagnostics.stage = USB_LOADER_DISK_INIT;
    err = RM_FREERTOS_PLUS_FAT_DiskInit(
        &g_rm_freertos_plus_fat0_ctrl,
        &g_rm_freertos_plus_fat0_disk_cfg,
        &s_usb_disk
    );

    if (FSP_SUCCESS != err)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fsp_error = (int32_t) err;
        tm_printf(
            (UB *)"[USB] DiskInit failed: %d\n",
            err
        );

        return err;
    }

    tm_putstring(
        (UB *)"[USB] FF_Mount...\n"
    );

    g_usb_loader_diagnostics.stage = USB_LOADER_MOUNT;
    ff_err = FF_Mount(
        &s_usb_disk,
        USB_LOADER_PARTITION_NUMBER
    );

    if (FF_ERR_NONE != ff_err)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fat_error = (int32_t) ff_err;
        tm_printf(
            (UB *)"[USB] FF_Mount failed: %d\n",
            ff_err
        );

        (void) RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

        return FSP_ERR_INVALID_DATA;
    }

    int fs_add_result = FF_FS_Add("/", &s_usb_disk);

    if (pdTRUE != fs_add_result)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fsp_error = (int32_t) FSP_ERR_INTERNAL;
        tm_putstring(
            (UB *)"[USB] FF_FS_Add failed.\n"
        );

        (void) RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

        return FSP_ERR_INTERNAL;
    }

    tm_putstring(
        (UB *)"[USB] filesystem root registered.\n"
    );

    s_usb_mounted = 1U;

    tm_putstring(
        (UB *)"[USB] FAT filesystem mounted.\n"
    );

    return FSP_SUCCESS;
}


LOCAL void usb_loader_unmount(void)
{
    if (0U == s_usb_mounted)
    {
        return;
    }

    /* Remove the root's IO-manager reference before DiskDeinit frees it.
     * The device is already detached: do not flush/unmount through USB here.
     * This reader closes its files before returning to the event loop.
     */
    FF_FS_Remove("/");

    fsp_err_t err =
        RM_FREERTOS_PLUS_FAT_DiskDeinit(
            &g_rm_freertos_plus_fat0_ctrl,
            &s_usb_disk
        );

    if (FSP_SUCCESS != err)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fsp_error = (int32_t) err;
        tm_printf(
            (UB *)"[USB] DiskDeinit failed: %d\n",
            err
        );
    }
    else
    {
        tm_putstring(
            (UB *)"[USB] disk deinitialized.\n"
        );
    }

    s_usb_mounted = 0U;
}


LOCAL void usb_loader_task_entry(INT stacd, void *exinf)
{
    fsp_err_t err;

    usb_event_info_t event_info = {0};
    usb_status_t usb_event = USB_STATUS_POWERED;

    uint8_t configured = 0U;
    uint32_t poll_return_count = 0U;

    (void) stacd;
    (void) exinf;

    tm_putstring(
        (UB *)"[USB] task started.\n"
    );

    /*
     * Open the FreeRTOS+FAT port.
     *
     * In this project BSP_CFG_RTOS == 0, so this uses the
     * non-FreeRTOS path while opening the underlying USB
     * block-media/HMSC/basic stack.
     */
    g_usb_loader_diagnostics.stage = USB_LOADER_OPENING;
    err = RM_FREERTOS_PLUS_FAT_Open(
        &g_rm_freertos_plus_fat0_ctrl,
        &g_rm_freertos_plus_fat0_cfg
    );

    if (FSP_SUCCESS != err)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fsp_error = (int32_t) err;
        tm_printf(
            (UB *)"[USB] open failed: fsp_err=%d\n",
            err
        );

        tk_ext_tsk();
        return;
    }

    tm_putstring(
        (UB *)"[USB] host initialized.\n"
    );

    g_usb_loader_diagnostics.stage = USB_LOADER_WAIT_DEVICE;

    while (1)
    {
        err = g_basic0.p_api->eventGet(
            &event_info,
            &usb_event
        );

        if (FSP_SUCCESS != err)
        {
            g_usb_loader_diagnostics.last_fsp_error = (int32_t) err;
            tm_printf(
                (UB *)"[USB] eventGet failed: fsp_err=%d\n",
                err
            );

            tk_dly_tsk(100);
            continue;
        }

        /*
        * If this counter stops after inserting the USB stick,
        * eventGet() itself is not returning.
        */
        poll_return_count++;
        g_usb_loader_diagnostics.event_poll_count = poll_return_count;

        if ((poll_return_count % 100U) == 0U)
        {
            tm_putstring(
                (UB *)"[USB] eventGet alive.\n"
            );
        }

        /*
        * Log every USB event instead of silently ignoring
        * events other than CONFIGURED / DETACH.
        */
        if (USB_STATUS_NONE != usb_event)
        {
            g_usb_loader_diagnostics.last_usb_event = (uint32_t) usb_event;
            tm_printf(
                (UB *)"[USB] event=%d device_address=%u\n",
                usb_event,
                event_info.device_address
            );
        }

        switch (usb_event)
        {
            case USB_STATUS_CONFIGURED:
            {
                if (0U == configured)
                {
                    g_usb_loader_diagnostics.failed = 0U;
                    g_usb_loader_diagnostics.last_fsp_error = 0;
                    g_usb_loader_diagnostics.last_fat_error = 0;
                    g_usb_loader_diagnostics.frame_index = 0U;
                    g_usb_loader_diagnostics.frames_published = 0U;
                    g_usb_loader_diagnostics.frame_count = 0U;
                    g_usb_loader_diagnostics.target_fps = 0U;
                    g_usb_loader_diagnostics.playback_elapsed_ms = 0U;
                    tm_printf(
                        (UB *)"[USB] configured: device_address=%u\n",
                        event_info.device_address
                    );

                    err = usb_loader_mount(
                        &event_info
                    );

                    if (FSP_SUCCESS == err)
                    {
                        configured = 1U;
                        usb_loader_stream_selected_video();
                    }
                    else
                    {
                        g_usb_loader_diagnostics.failed = 1U;
                        g_usb_loader_diagnostics.last_fsp_error = (int32_t) err;
                        tm_putstring(
                            (UB *)"[USB] filesystem mount failed.\n"
                        );
                    }
                }

                break;
            }

            case USB_STATUS_DETACH:
            {
                g_usb_loader_diagnostics.detach_count++;
                usb_loader_unmount();

                configured = 0U;
                g_usb_loader_diagnostics.stage = USB_LOADER_WAIT_DEVICE;

                tm_putstring(
                    (UB *)"[USB] detached.\n"
                );

                break;
            }

            default:
            {
                break;
            }
        }

        tk_dly_tsk(10);
    }
}


LOCAL uint8_t usb_loader_read_config(
    uint32_t * selected_index,
    uint32_t * target_fps)
{
    if ((NULL == selected_index) ||
        (NULL == target_fps))
    {
        return 0U;
    }


    FF_FILE * file =
        ff_fopen(
            USB_LOADER_SELECT_PATH,
            "r"
        );

    if (NULL == file)
    {
        g_usb_loader_diagnostics.last_fat_error = (int32_t) stdioGET_ERRNO();
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT open failed.\n"
        );

        return 0U;
    }


    uint8_t buffer[32] = {0U};

    size_t read_size =
        ff_fread(
            buffer,
            1U,
            sizeof(buffer) - 1U,
            file
        );

    (void) ff_fclose(file);


    if (0U == read_size)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT empty.\n"
        );

        return 0U;
    }


    /*
     * Format:
     *
     * line 1 : video index
     * line 2 : target FPS
     *
     * Example:
     *
     * 10
     * 30
     */
    uint32_t values[2] =
    {
        0U,
        0U
    };

    uint32_t value_index = 0U;
    uint32_t digits = 0U;


    for (size_t i = 0U;
         (i < read_size) &&
         (value_index < 2U);
         i++)
    {
        uint8_t c = buffer[i];


        if ((c >= (uint8_t) '0') &&
            (c <= (uint8_t) '9'))
        {
            values[value_index] =
                (values[value_index] * 10U) +
                (uint32_t)
                (c - (uint8_t) '0');

            digits++;
        }
        else if ((c == (uint8_t) '\r') ||
                 (c == (uint8_t) '\n') ||
                 (c == (uint8_t) ' ')  ||
                 (c == (uint8_t) '\t'))
        {
            if (0U != digits)
            {
                value_index++;
                digits = 0U;
            }
        }
        else
        {
            tm_putstring(
                (UB *)"[Dataset] invalid SELECT.TXT.\n"
            );

            return 0U;
        }
    }


    /*
     * Account for the final number if the file does
     * not end with a newline.
     */
    if ((0U != digits) &&
        (value_index < 2U))
    {
        value_index++;
    }


    if (2U != value_index)
    {
        tm_putstring(
            (UB *)"[Dataset] SELECT.TXT requires "
                   "video index and FPS.\n"
        );

        return 0U;
    }


    if (values[0] >
        USB_LOADER_MAX_VIDEO_INDEX)
    {
        tm_putstring(
            (UB *)"[Dataset] selected index too large.\n"
        );

        return 0U;
    }


    if (values[1] >
        USB_LOADER_MAX_TARGET_FPS)
    {
        tm_putstring(
            (UB *)"[FPS] target FPS too large.\n"
        );

        return 0U;
    }


    *selected_index =
        values[0];

    *target_fps =
        values[1];


    return 1U;
}


LOCAL void usb_loader_make_video_path(
    uint32_t index,
    char path[12])
{
    /*
     * "/VID000.Y56"
     *
     * 11 characters + '\0'
     */
    path[0]  = '/';
    path[1]  = 'V';
    path[2]  = 'I';
    path[3]  = 'D';

    path[4] =
        (char) ('0' + ((index / 100U) % 10U));

    path[5] =
        (char) ('0' + ((index / 10U) % 10U));

    path[6] =
        (char) ('0' + (index % 10U));

    path[7]  = '.';
    path[8]  = 'Y';
    path[9]  = '5';
    path[10] = '6';
    path[11] = '\0';
}


LOCAL size_t usb_loader_read_exact(
    FF_FILE * file,
    uint8_t * destination,
    size_t bytes_to_read)
{
    if ((NULL == file) ||
        (NULL == destination))
    {
        return 0U;
    }


    size_t total_read = 0U;

    while (total_read < bytes_to_read)
    {
        size_t read_size =
            ff_fread(
                destination + total_read,
                1U,
                bytes_to_read - total_read,
                file
            );

        if (0U == read_size)
        {
            break;
        }

        total_read += read_size;
    }


    return total_read;
}


#if USB_LOADER_ENABLE_RAW_BENCHMARK
LOCAL void usb_loader_run_raw_benchmark(void)
{
    uint32_t slot = 0U;

    uint8_t * buffer =
        video_source_acquire_write_buffer(
            &slot
        );

    if (NULL == buffer)
    {
        tm_putstring(
            (UB *)"[USB-Bench] no SDRAM buffer available.\n"
        );

        return;
    }


    SYSTIM start_time;
    SYSTIM end_time;

    ER time_err =
        tk_get_otm(
            &start_time
        );

    if (time_err < E_OK)
    {
        video_source_cancel_write_buffer(
            slot
        );

        tm_putstring(
            (UB *)"[USB-Bench] tk_get_otm start failed.\n"
        );

        return;
    }


    uint32_t completed = 0U;

    for (uint32_t i = 0U;
         i < USB_BENCHMARK_FRAME_COUNT;
         i++)
    {
        uint32_t block_address =
            USB_BENCHMARK_START_BLOCK +
            (i * USB_BENCHMARK_BLOCKS_PER_FRAME);

        fsp_err_t err =
            g_rm_block_media0.p_api->read(
                g_rm_block_media0.p_ctrl,
                buffer,
                block_address,
                USB_BENCHMARK_BLOCKS_PER_FRAME
            );

        if (FSP_SUCCESS != err)
        {
            tm_printf(
                (UB *)"[USB-Bench] read failed: "
                       "index=%u block=%u err=%d\n",
                i,
                block_address,
                err
            );

            break;
        }

        completed++;
    }


    time_err =
        tk_get_otm(
            &end_time
        );


    video_source_cancel_write_buffer(
        slot
    );


    if (time_err < E_OK)
    {
        tm_putstring(
            (UB *)"[USB-Bench] tk_get_otm end failed.\n"
        );

        return;
    }


    uint64_t start_ms =
        ((uint64_t) (uint32_t) start_time.hi << 32) |
        start_time.lo;

    uint64_t end_ms =
        ((uint64_t) (uint32_t) end_time.hi << 32) |
        end_time.lo;

    uint64_t elapsed_ms =
        end_ms - start_ms;


    if ((0U == completed) ||
        (0U == elapsed_ms))
    {
        return;
    }


    uint64_t total_bytes =
        (uint64_t) completed *
        USB_BENCHMARK_BLOCKS_PER_FRAME *
        USB_BENCHMARK_BLOCK_SIZE_BYTES;


    /*
     * MB/s x 1000.
     */
    uint32_t mbps_x1000 =
        (uint32_t)
        (
            (total_bytes * 1000ULL) /
            elapsed_ms /
            1000ULL
        );


    tm_printf(
        (UB *)"[USB-Bench] "
               "frames=%u "
               "bytes=%u "
               "elapsed_ms=%u "
               "MBps=%u.%03u\n",
        completed,
        (uint32_t) total_bytes,
        (uint32_t) elapsed_ms,
        mbps_x1000 / 1000U,
        mbps_x1000 % 1000U
    );
}
#endif


LOCAL void usb_loader_stream_selected_video(void)
{
    uint32_t selected_index = 0U;
    uint32_t target_fps = 0U;

    g_usb_loader_diagnostics.stage = USB_LOADER_READ_SELECT;

    if (0U ==
        usb_loader_read_config(
            &selected_index,
            &target_fps))
    {
        g_usb_loader_diagnostics.failed = 1U;
        return;
    }


    /*
     * USB owns the frame schedule and FPS reporting, even with Display OFF.
     * Reset timing on every replay; never inherit the previous deadline.
     *
     * 0 means unlimited.
     */
    fps_control_init(
        target_fps
    );
    g_usb_loader_diagnostics.target_fps = target_fps;


    tm_printf(
        (UB *)"[FPS] configured from SELECT.TXT: %u\n",
        target_fps
    );


    char path[12];

    usb_loader_make_video_path(
        selected_index,
        path
    );


    tm_printf(
        (UB *)"[Dataset] selected=%u file=%s\n",
        selected_index,
        path
    );


    g_usb_loader_diagnostics.stage = USB_LOADER_OPEN_VIDEO;
    FF_FILE * file =
        ff_fopen(
            path,
            "rb"
        );

    if (NULL == file)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fat_error = (int32_t) stdioGET_ERRNO();
        tm_printf(
            (UB *)"[Dataset] file not found: %s\n",
            path
        );

        return;
    }


    /*
     * File size is used only to determine whether the RAW file
     * consists of complete frames.
     *
     * The complete file is NOT read here.
     */
    size_t file_size =
        ff_filelength(file);

    tm_printf(
        (UB *)"[Dataset] file_size=%u bytes\n",
        (uint32_t) file_size
    );


    if (0U == file_size)
    {
        g_usb_loader_diagnostics.failed = 1U;
        tm_putstring(
            (UB *)"[Dataset] empty RAW file.\n"
        );

        (void) ff_fclose(file);

        return;
    }


    /*
    * .Y56 contains tightly-packed 224 x 168 RGB565 frames.
    */
    if ((file_size %
        VIDEO_SOURCE_FILE_FRAME_BYTES) != 0U)
    {
        g_usb_loader_diagnostics.failed = 1U;
        tm_printf(
            (UB *)"[Dataset] invalid Y56 size: "
                "bytes=%u file_frame_bytes=%u remainder=%u\n",
            (uint32_t) file_size,
            VIDEO_SOURCE_FILE_FRAME_BYTES,
            (uint32_t)
            (file_size %
            VIDEO_SOURCE_FILE_FRAME_BYTES)
        );

        (void) ff_fclose(file);

        return;
    }


    uint32_t frame_count =
        (uint32_t)
        (file_size /
        VIDEO_SOURCE_FILE_FRAME_BYTES);

    g_usb_loader_diagnostics.frame_count = frame_count;

    tm_printf(
        (UB *)"[Dataset] streaming start: "
            "frames=%u "
            "file_frame_bytes=%u "
            "cache_frame_bytes=%u "
            "stride=%u\n",
        frame_count,
        VIDEO_SOURCE_FILE_FRAME_BYTES,
        VIDEO_SOURCE_FRAME_BYTES,
        VIDEO_SOURCE_STRIDE_BYTES
    );


    uint32_t frames_published = 0U;
    uint32_t first_publish_ms = 0U;

    g_usb_loader_diagnostics.playback_count++;


    for (uint32_t frame_index = 0U;
         frame_index < frame_count;
         frame_index++)
    {
        uint32_t slot = 0U;
        uint8_t * frame_buffer = NULL;

        g_usb_loader_diagnostics.frame_index = frame_index;
        g_usb_loader_diagnostics.stage = USB_LOADER_WAIT_BUFFER;

        /*
         * Wait until the next SDRAM input buffer becomes EMPTY.
         *
         * This provides back-pressure:
         * USB cannot overwrite a frame still being used
         * by any enabled consumer.
         */
        while (NULL == frame_buffer)
        {
            frame_buffer =
                video_source_acquire_write_buffer(
                    &slot
                );

            if (NULL == frame_buffer)
            {
                tk_dly_tsk(1);
            }
        }


        /*
        * Read one tightly-packed 224 x 168 RGB565 frame.
        *
        * USB layout:
        *   448 bytes/line x 168 lines
        *
        * First read it contiguously into the beginning of
        * the Frame Cache buffer.
        */
        g_usb_loader_diagnostics.stage = USB_LOADER_READ_FRAME;
        fps_control_usb_read_begin(
            frame_index
        );

        size_t read_size =
            usb_loader_read_exact(
                file,
                frame_buffer,
                VIDEO_SOURCE_FILE_FRAME_BYTES
            );

        fps_control_usb_read_end();


        if (VIDEO_SOURCE_FILE_FRAME_BYTES !=
            read_size)
        {
            int fat_errno =
                stdioGET_ERRNO();

            g_usb_loader_diagnostics.failed = 1U;
            g_usb_loader_diagnostics.last_fat_error = (int32_t) fat_errno;
            video_source_cancel_write_buffer(
                slot
            );

            tm_printf(
                (UB *)"[Dataset] frame read failed: "
                    "frame=%u expected=%u actual=%u errno=%d\n",
                frame_index,
                VIDEO_SOURCE_FILE_FRAME_BYTES,
                (uint32_t) read_size,
                fat_errno
            );

            break;
        }


        /*
        * Expand the tightly-packed USB frame in-place
        * to reproduce the VIN SDRAM layout.
        *
        * USB:
        *   row y starts at y * 448
        *
        * VIN-compatible Frame Cache:
        *   row y starts at y * 2048
        *
        * Move from the last row toward the first row so
        * that expanding the layout cannot overwrite source
        * rows which have not yet been moved.
        */
        for (uint32_t y = VIDEO_SOURCE_HEIGHT;
            y > 1U;
            y--)
        {
            uint32_t const row =
                y - 1U;

            uint8_t * destination =
                frame_buffer +
                (row * VIDEO_SOURCE_STRIDE_BYTES);

            uint8_t * source =
                frame_buffer +
                (row * VIDEO_SOURCE_ACTIVE_LINE_BYTES);

            memmove(
                destination,
                source,
                VIDEO_SOURCE_ACTIVE_LINE_BYTES
            );
        }


        /* Pace complete frames at the producer, independently of Display.
         * Reading and stride expansion count toward the frame period.
         */
        g_usb_loader_diagnostics.stage = USB_LOADER_WAIT_FPS;
        fps_control_wait_before_frame();

        /* UINT32_MAX is the existing invalid-frame sentinel downstream. */
        if (UINT32_MAX == s_next_stream_frame_index)
        {
            s_next_stream_frame_index = 0U;
        }

        uint32_t const stream_frame_index = s_next_stream_frame_index++;
        SYSTIM publish_time;
        if (E_OK == tk_get_otm(&publish_time))
        {
            if (0U == frames_published)
            {
                first_publish_ms = publish_time.lo;
            }
            g_usb_loader_diagnostics.playback_elapsed_ms =
                publish_time.lo - first_publish_ms;
        }

        /* Transfer the complete frame to all enabled consumers. */
        video_source_publish_write_buffer(
            slot,
            stream_frame_index
        );


        frames_published++;
        g_usb_loader_diagnostics.frames_published = frames_published;
        g_usb_loader_diagnostics.stream_frame_index = stream_frame_index;

        /* The existing [FPS] report measures USB publication in USB mode.
         * Use the file-local index so every replay resets measurement.
         */
        fps_control_frame_presented(frame_index);

        /* A free next buffer does not guarantee that lower-priority tasks
         * have run. Sleep explicitly so NPU and IPC can consume this frame.
         * tk_dly_tsk(1) is rounded to the configured kernel tick resolution.
         */
        tk_dly_tsk(USB_LOADER_FRAME_YIELD_MS);
    }

    /* A gap prevents Motion from comparing the last frame of this replay
     * with the first of the next one. Do not reset shared consumer state.
     */
    if (0U != frames_published)
    {
        s_next_stream_frame_index++;
    }


    int close_result =
        ff_fclose(file);

    if (0 != close_result)
    {
        g_usb_loader_diagnostics.failed = 1U;
        g_usb_loader_diagnostics.last_fat_error = (int32_t) stdioGET_ERRNO();
        tm_printf(
            (UB *)"[Dataset] close failed: %d\n",
            close_result
        );
    }

    if ((frames_published == frame_count) &&
        (0U == g_usb_loader_diagnostics.failed))
    {
        g_usb_loader_diagnostics.stage = USB_LOADER_FINISHED;
    }


    tm_printf(
        (UB *)"[Dataset] streaming end: "
               "published=%u/%u frames\n",
        frames_published,
        frame_count
    );
}
